-- =============================================================
-- Express Demo: 20 fake stations + operational signals + traffic baseline
-- + customer_demo_locations for Sarah, Khalid, Omar
-- Run after migration: express_demo_locations_and_traffic
-- Idempotent: deletes prior express_demo pool rows then re-seeds
-- =============================================================

BEGIN;

DELETE FROM public.station_operational_signals
WHERE station_id IN (SELECT id FROM public.stations WHERE station_type = 'express_demo');

DELETE FROM public.stations WHERE station_type = 'express_demo';

INSERT INTO public.stations (
  id, name, city, region, lat, lng, ev_charging, car_care, fnb, services, facilities, address, operating_hours, station_type
) VALUES
('DEMO-EXP-01', 'ADNOC Express Marina Walk', 'Dubai', 'Dubai', 25.0774, 55.1392, true,
  ARRAY['Express Wash','Interior Clean']::text[], ARRAY['Starbucks','Pret']::text[],
  ARRAY['Fuel','EV','Car Care']::text[], ARRAY['Prayer Room','ATM','Kids Zone']::text[],
  'Marina Walk, Dubai Marina', '24/7', 'express_demo'),
('DEMO-EXP-02', 'ADNOC Express JLT Cluster Q', 'Dubai', 'Dubai', 25.0689, 55.1421, true,
  ARRAY['Quick Lube','Tire Check']::text[], ARRAY['Costa','Krispy Kreme']::text[],
  ARRAY['Fuel','Shop','Loyalty Desk']::text[], ARRAY['ATM','Wi-Fi Lounge']::text[],
  'JLT, Dubai', '24/7', 'express_demo'),
('DEMO-EXP-03', 'ADNOC Express Emirates Hills', 'Dubai', 'Dubai', 25.0712, 55.1810, false,
  ARRAY['Premium Wash','Detailing']::text[], ARRAY['Cafe Arabic','Cold Stone']::text[],
  ARRAY['Fuel','Car Care']::text[], ARRAY['Prayer Room','Valet']::text[],
  'Al Thanyah Fourth, Emirates Hills', '24/7', 'express_demo'),
('DEMO-EXP-04', 'ADNOC Express Jebel Ali South', 'Dubai', 'Dubai', 25.0450, 55.1180, true,
  ARRAY['Express Wash']::text[], ARRAY['McDonalds','Subway']::text[],
  ARRAY['Fuel','EV','Truck Lane']::text[], ARRAY['ATM','Truck Parking']::text[],
  'Jebel Ali Village', '24/7', 'express_demo'),
('DEMO-EXP-05', 'ADNOC Express JAFZA Gate', 'Dubai', 'Dubai', 25.0120, 55.1050, true,
  ARRAY['Fleet Wash','Oil Change']::text[], ARRAY['Starbucks']::text[],
  ARRAY['Fuel','EV','Fleet']::text[], ARRAY['Prayer Room','ATM']::text[],
  'JAFZA, Dubai', '24/7', 'express_demo'),
('DEMO-EXP-06', 'ADNOC Express Jumeirah Beach', 'Dubai', 'Dubai', 25.1020, 55.1380, true,
  ARRAY['Express Wash','Wax']::text[], ARRAY['Costa','Baskin Robbins']::text[],
  ARRAY['Fuel','EV','Beach Pickup']::text[], ARRAY['EV Lounge','Showers']::text[],
  'Jumeirah Beach Rd', '24/7', 'express_demo'),
('DEMO-EXP-07', 'ADNOC Express Al Barsha South', 'Dubai', 'Dubai', 25.0950, 55.2100, true,
  ARRAY['Quick Lube','AC Check']::text[], ARRAY['KFC','Pizza Hut']::text[],
  ARRAY['Fuel','EV','Car Care']::text[], ARRAY['Prayer Room','ATM']::text[],
  'Al Barsha South', '24/7', 'express_demo'),
('DEMO-EXP-08', 'ADNOC Express Motor City', 'Dubai', 'Dubai', 25.0455, 55.2420, false,
  ARRAY['Express Wash','Tire Shop']::text[], ARRAY['Tim Hortons']::text[],
  ARRAY['Fuel','Car Care']::text[], ARRAY['ATM','Motorsport Shop']::text[],
  'Motor City, Dubai', '24/7', 'express_demo'),
('DEMO-EXP-09', 'ADNOC Express DIP', 'Dubai', 'Dubai', 25.0280, 55.1680, true,
  ARRAY['Heavy Wash','Underbody']::text[], ARRAY['Starbucks']::text[],
  ARRAY['Fuel','EV','Fleet']::text[], ARRAY['Truck Wash','ATM']::text[],
  'Dubai Investment Park', '24/7', 'express_demo'),
('DEMO-EXP-10', 'ADNOC Express Silicon Oasis', 'Dubai', 'Dubai', 25.1180, 55.3850, true,
  ARRAY['Express Wash','Interior']::text[], ARRAY['Costa','Subway']::text[],
  ARRAY['Fuel','EV','Tech Kiosk']::text[], ARRAY['Prayer Room','EV Lounge']::text[],
  'Dubai Silicon Oasis', '24/7', 'express_demo'),
('DEMO-EXP-11', 'ADNOC Express Mirdif City Centre', 'Dubai', 'Dubai', 25.2280, 55.4090, true,
  ARRAY['Premium Wash','Detail']::text[], ARRAY['Starbucks','Shake Shack']::text[],
  ARRAY['Fuel','EV','Retail']::text[], ARRAY['ATM','Family Lounge']::text[],
  'Mirdif', '24/7', 'express_demo'),
('DEMO-EXP-12', 'ADNOC Express Deira Waterfront', 'Dubai', 'Dubai', 25.2680, 55.3180, false,
  ARRAY['Express Wash']::text[], ARRAY['Cafe Arabic']::text[],
  ARRAY['Fuel','Shop']::text[], ARRAY['Prayer Room','ATM']::text[],
  'Deira', '24/7', 'express_demo'),
('DEMO-EXP-13', 'ADNOC Express Al Khail East', 'Dubai', 'Dubai', 25.1120, 55.2880, true,
  ARRAY['Quick Lube','AC Service']::text[], ARRAY['McDonalds']::text[],
  ARRAY['Fuel','EV']::text[], ARRAY['ATM']::text[],
  'Al Khail Rd', '24/7', 'express_demo'),
('DEMO-EXP-14', 'ADNOC Express Al Qudra', 'Dubai', 'Dubai', 24.9980, 55.2580, true,
  ARRAY['Off-road Wash']::text[], ARRAY['Starbucks']::text[],
  ARRAY['Fuel','EV','Desert Stop']::text[], ARRAY['Picnic','ATM']::text[],
  'Al Qudra', '24/7', 'express_demo'),
('DEMO-EXP-15', 'ADNOC Express Sharjah Industrial', 'Sharjah', 'Sharjah', 25.3180, 55.4580, true,
  ARRAY['Fleet Wash','Lube']::text[], ARRAY['Costa']::text[],
  ARRAY['Fuel','EV','Fleet']::text[], ARRAY['Truck Lane','ATM']::text[],
  'Industrial Area 10', '24/7', 'express_demo'),
('DEMO-EXP-16', 'ADNOC Express Al Nahda', 'Sharjah', 'Sharjah', 25.2980, 55.3780, false,
  ARRAY['Express Wash']::text[], ARRAY['KFC','Krispy Kreme']::text[],
  ARRAY['Fuel','Car Care']::text[], ARRAY['Prayer Room','ATM']::text[],
  'Al Nahda, Sharjah', '24/7', 'express_demo'),
('DEMO-EXP-17', 'ADNOC Express Ajman Corniche', 'Ajman', 'Ajman', 25.4180, 55.4380, true,
  ARRAY['Express Wash','Interior']::text[], ARRAY['Starbucks']::text[],
  ARRAY['Fuel','EV']::text[], ARRAY['Beach View','ATM']::text[],
  'Ajman Corniche', '24/7', 'express_demo'),
('DEMO-EXP-18', 'ADNOC Express RAK Al Nakheel', 'Ras Al Khaimah', 'Ras Al Khaimah', 25.7880, 55.9480, true,
  ARRAY['Premium Wash']::text[], ARRAY['Costa','Subway']::text[],
  ARRAY['Fuel','EV']::text[], ARRAY['Prayer Room','ATM']::text[],
  'Al Nakheel, RAK', '24/7', 'express_demo'),
('DEMO-EXP-19', 'ADNOC Express Abu Dhabi MBZ', 'Abu Dhabi', 'Abu Dhabi', 24.3880, 54.5280, true,
  ARRAY['Express Wash','Quick Lube']::text[], ARRAY['Starbucks']::text[],
  ARRAY['Fuel','EV','Car Care']::text[], ARRAY['EV Lounge','ATM']::text[],
  'Mohamed Bin Zayed City', '24/7', 'express_demo'),
('DEMO-EXP-20', 'ADNOC Express Yas Island', 'Abu Dhabi', 'Abu Dhabi', 24.4980, 54.6080, true,
  ARRAY['Premium Wash','Detailing']::text[], ARRAY['Shake Shack','Starbucks']::text[],
  ARRAY['Fuel','EV','Events']::text[], ARRAY['Family Zone','ATM']::text[],
  'Yas Island', '24/7', 'express_demo'),
('DEMO-EXP-21', 'ADNOC Express The Greens', 'Dubai', 'Dubai', 25.0958, 55.1668, true,
  ARRAY['Express Wash','Interior Clean']::text[], ARRAY['Costa','Bakery']::text[],
  ARRAY['Fuel','EV','Shop']::text[], ARRAY['ATM','Wi-Fi Lounge']::text[],
  'The Greens, Dubai', '24/7', 'express_demo'),
('DEMO-EXP-22', 'ADNOC Express Barsha Heights (TECOM)', 'Dubai', 'Dubai', 25.0952, 55.1749, true,
  ARRAY['Quick Lube','Tire Check']::text[], ARRAY['Starbucks']::text[],
  ARRAY['Fuel','EV','Car Care']::text[], ARRAY['Prayer Room','ATM']::text[],
  'Barsha Heights, Dubai', '24/7', 'express_demo'),
('DEMO-EXP-23', 'ADNOC Express Dubai Hills', 'Dubai', 'Dubai', 25.1096, 55.2396, true,
  ARRAY['Quick Lube','AC Check']::text[], ARRAY['Cafe','Bakery']::text[],
  ARRAY['Fuel','EV','Car Care']::text[], ARRAY['ATM']::text[],
  'Dubai Hills Estate, Dubai', '24/7', 'express_demo'),
('DEMO-EXP-24', 'ADNOC Express Downtown (DIFC Edge)', 'Dubai', 'Dubai', 25.2060, 55.2710, true,
  ARRAY['Express Wash']::text[], ARRAY['Coffee','Sandwiches']::text[],
  ARRAY['Fuel','EV','Shop']::text[], ARRAY['ATM']::text[],
  'DIFC / Downtown, Dubai', '24/7', 'express_demo'),
('DEMO-EXP-26', 'ADNOC Express Al Quoz', 'Dubai', 'Dubai', 25.1315, 55.2232, true,
  ARRAY['Tire Shop','Oil Change']::text[], ARRAY['Coffee']::text[],
  ARRAY['Fuel','EV','Fleet']::text[], ARRAY['ATM','Truck Lane']::text[],
  'Al Quoz, Dubai', '24/7', 'express_demo'),
('DEMO-EXP-27', 'ADNOC Express Palm Jumeirah', 'Dubai', 'Dubai', 25.1123, 55.1387, true,
  ARRAY['Express Wash']::text[], ARRAY['Cafe']::text[],
  ARRAY['Fuel','EV','Beach Pickup']::text[], ARRAY['Showers']::text[],
  'Palm Jumeirah, Dubai', '24/7', 'express_demo'),
('DEMO-EXP-28', 'ADNOC Express Al Wasl', 'Dubai', 'Dubai', 25.2010, 55.2490, true,
  ARRAY['Express Wash','Wax']::text[], ARRAY['Coffee','Bakery']::text[],
  ARRAY['Fuel','EV']::text[], ARRAY['ATM']::text[],
  'Al Wasl, Dubai', '24/7', 'express_demo'),
('DEMO-EXP-29', 'ADNOC Express Dubai Creek Harbour', 'Dubai', 'Dubai', 25.2086, 55.3543, true,
  ARRAY['Express Wash']::text[], ARRAY['Coffee']::text[],
  ARRAY['Fuel','EV','Shop']::text[], ARRAY['ATM']::text[],
  'Dubai Creek Harbour, Dubai', '24/7', 'express_demo'),
('DEMO-EXP-30', 'ADNOC Express Al Safa', 'Dubai', 'Dubai', 25.1795, 55.2467, true,
  ARRAY['Interior Clean','Quick Lube']::text[], ARRAY['Cafe']::text[],
  ARRAY['Fuel','EV','Car Care']::text[], ARRAY['Prayer Room','ATM']::text[],
  'Al Safa, Dubai', '24/7', 'express_demo');

INSERT INTO public.station_operational_signals (
  id, station_id, coffee_prep_time_minutes, car_wash_queue_minutes, interior_cleaning_available,
  ev_chargers_available, avg_ev_charge_time_minutes, cold_beverage_stock_high, approach_traffic_minutes
) VALUES
(gen_random_uuid(), 'DEMO-EXP-01', 4, 12, true, 4, 28, true, 11),
(gen_random_uuid(), 'DEMO-EXP-02', 6, 18, true, 2, 35, true, 16),
(gen_random_uuid(), 'DEMO-EXP-03', 3, 8, false, 0, 0, true, 7),
(gen_random_uuid(), 'DEMO-EXP-04', 5, 22, true, 6, 32, false, 19),
(gen_random_uuid(), 'DEMO-EXP-05', 7, 25, false, 8, 30, true, 21),
(gen_random_uuid(), 'DEMO-EXP-06', 5, 15, true, 3, 27, true, 9),
(gen_random_uuid(), 'DEMO-EXP-07', 4, 20, true, 5, 33, true, 14),
(gen_random_uuid(), 'DEMO-EXP-08', 6, 10, false, 0, 0, true, 6),
(gen_random_uuid(), 'DEMO-EXP-09', 8, 30, true, 10, 40, false, 22),
(gen_random_uuid(), 'DEMO-EXP-10', 5, 14, true, 4, 29, true, 12),
(gen_random_uuid(), 'DEMO-EXP-11', 4, 11, true, 5, 26, true, 10),
(gen_random_uuid(), 'DEMO-EXP-12', 6, 9, false, 0, 0, false, 8),
(gen_random_uuid(), 'DEMO-EXP-13', 5, 17, true, 3, 31, true, 15),
(gen_random_uuid(), 'DEMO-EXP-14', 7, 6, false, 2, 45, true, 5),
(gen_random_uuid(), 'DEMO-EXP-15', 9, 28, true, 12, 38, true, 18),
(gen_random_uuid(), 'DEMO-EXP-16', 5, 13, false, 0, 0, true, 13),
(gen_random_uuid(), 'DEMO-EXP-17', 4, 10, true, 3, 28, true, 9),
(gen_random_uuid(), 'DEMO-EXP-18', 6, 12, true, 4, 30, true, 11),
(gen_random_uuid(), 'DEMO-EXP-19', 5, 16, true, 6, 32, true, 14),
(gen_random_uuid(), 'DEMO-EXP-20', 3, 9, true, 4, 25, true, 8),
(gen_random_uuid(), 'DEMO-EXP-21', 4, 9, true, 6, 26, true, 4),
(gen_random_uuid(), 'DEMO-EXP-22', 5, 12, true, 5, 28, true, 6),
(gen_random_uuid(), 'DEMO-EXP-23', 4, 10, true, 8, 29, true, 5),
(gen_random_uuid(), 'DEMO-EXP-24', 6, 14, true, 4, 30, true, 7),
(gen_random_uuid(), 'DEMO-EXP-26', 7, 18, true, 5, 33, true, 8),
(gen_random_uuid(), 'DEMO-EXP-27', 4, 10, true, 4, 28, true, 6),
(gen_random_uuid(), 'DEMO-EXP-28', 5, 12, true, 4, 29, true, 7),
(gen_random_uuid(), 'DEMO-EXP-29', 5, 12, true, 6, 30, true, 8),
(gen_random_uuid(), 'DEMO-EXP-30', 4, 10, true, 6, 28, true, 6);

INSERT INTO public.customer_demo_locations (customer_id, label, lat, lng)
SELECT c.id, v.label, v.lat, v.lng
FROM public.customers c
JOIN (VALUES
  ('Sarah', 'Greens Community East, Dubai', 25.1007300::double precision, 55.1704300::double precision),
  ('Khalid', 'Dubai Hills Estate, Dubai', 25.1062800::double precision, 55.2411700::double precision),
  ('Omar', 'Business Bay, Dubai', 25.1868200::double precision, 55.2673100::double precision)
) AS v(first_name, label, lat, lng) ON lower(c.first_name) = lower(v.first_name)
ON CONFLICT (customer_id) DO UPDATE SET
  label = EXCLUDED.label,
  lat = EXCLUDED.lat,
  lng = EXCLUDED.lng;

COMMIT;
